version: '2'
services:
        mysql-zabbix: 
                image: mysql:8
                command: mysqld --default-authentication-plugin=mysql_native_password
                restart: always
                volumes:
                        - /docker/mysql/zabbix/data:/var/lib/mysql
                environment:
                        - MYSQL_HOST=172.17.0.1
                        - MYSQL_ROOT_PASSWORD=secret
                        - MYSQL_DATABASE=zabbix
                        - MYSQL_USER=zabbix
                        - MYSQL_PASSWORD=zabbix
                ports:
                        - 3306:3306
        zabbix-server:
                image: zabbix/zabbix-server-mysql:ubuntu-4.4-latest
                restart: always
                environment:
                        - MYSQL_ROOT_PASSWORD=secret
                        - DB_SERVER_HOST=172.17.0.1
                        - DB_SERVER_PORT=3306
                        - MYSQL_USER=zabbix
                        - MYSQL_PASSWORD=zabbix
                        - MYSQL_DATABASE=zabbix
                ports:
                        - 10051:10051
                depends_on:
                        - mysql-zabbix
        zabbix-web:
                image: zabbix/zabbix-web-apache-mysql:ubuntu-4.4-latest
                restart: always
                environment:
                        - DB_SERVER_HOST=172.17.0.1
                        - DB_SERVER_PORT=3306
                        - MYSQL_USER=zabbix
                        - MYSQL_PASSWORD=zabbix
                        - MYSQL_DATABASE=zabbix
                        - ZBX_SERVER_HOST=172.17.0.1
                        - PHP_TZ=America/Sao_Paulo
                ports:
                        - 80:80
                depends_on:
                        - mysql-zabbix 
                        - zabbix-server
